# -*- coding: utf-8 -*-
"""Extension de la banque anglaise.

CES MOTS NE VIENNENT PAS DES LEXIQUES DU SITE : ils sont ajoutés pour le volume
et portent tous source="non-verifie". Choix délibéré, le même que pour le
néerlandais : uniquement du vocabulaire courant, concret et peu ambigu, là où
la traduction est stable. Les mots à double sens (bank, letter, right, still,
mark…) sont écartés exprès — un QCM ne sait pas afficher « ça dépend ».
Conventions reprises des lexiques anglais du site : verbes en « to + base »,
noms sans article, traduction française sans article.
"""
# (mot, [traductions], niveau, categorie, classe)
EXT = [
# ---------------- famille & personnes ----------------
("uncle",["oncle"],"A2","famille","nom"),("aunt",["tante"],"A2","famille","nom"),
("cousin",["cousin"],"A2","famille","nom"),("husband",["mari"],"A2","famille","nom"),
("wife",["épouse"],"A2","famille","nom"),("parents",["parents"],"A1","famille","nom"),
("child",["enfant"],"A1","famille","nom"),("neighbour",["voisin"],"A2","famille","nom"),
("colleague",["collègue"],"A2","famille","nom"),("nephew",["neveu"],"B1","famille","nom"),
("niece",["nièce"],"B1","famille","nom"),("twin",["jumeau"],"B1","famille","nom"),
("couple",["couple"],"A2","famille","nom"),("boy",["garçon"],"A1","famille","nom"),
("girl",["fille (enfant)"],"A1","famille","nom"),("adult",["adulte"],"B1","famille","nom"),
# ---------------- nourriture ----------------
("rice",["riz"],"A2","nourriture","nom"),("salt",["sel"],"A1","nourriture","nom"),
("sugar",["sucre"],"A1","nourriture","nom"),("butter",["beurre"],"A1","nourriture","nom"),
("oil",["huile"],"A2","nourriture","nom"),("soup",["soupe"],"A2","nourriture","nom"),
("salad",["salade"],"A2","nourriture","nom"),("chicken",["poulet"],"A2","nourriture","nom"),
("egg",["œuf"],"A1","nourriture","nom"),("tea",["thé"],"A1","nourriture","nom"),
("juice",["jus"],"A1","nourriture","nom"),("wine",["vin"],"A2","nourriture","nom"),
("beer",["bière"],"A2","nourriture","nom"),("cake",["gâteau"],"A2","nourriture","nom"),
("chocolate",["chocolat"],"A1","nourriture","nom"),("potato",["pomme de terre"],"A1","nourriture","nom"),
("vegetable",["légume"],"A1","nourriture","nom"),("breakfast",["petit-déjeuner"],"A2","nourriture","nom"),
("lunch",["déjeuner"],"A2","nourriture","nom"),("dinner",["dîner"],"A2","nourriture","nom"),
("meal",["repas"],"A2","nourriture","nom"),("plate",["assiette"],"A2","nourriture","nom"),
("fork",["fourchette"],"A2","nourriture","nom"),("knife",["couteau"],"A2","nourriture","nom"),
("spoon",["cuillère"],"A2","nourriture","nom"),("bottle",["bouteille"],"A1","nourriture","nom"),
("hunger",["faim"],"A2","nourriture","nom"),("thirst",["soif"],"A2","nourriture","nom"),
# ---------------- maison ----------------
("window",["fenêtre"],"A1","maison","nom"),("bedroom",["chambre"],"A1","maison","nom"),
("kitchen",["cuisine (pièce)"],"A1","maison","nom"),("garden",["jardin"],"A1","maison","nom"),
("wall",["mur"],"A2","maison","nom"),("roof",["toit"],"A2","maison","nom"),
("stairs",["escalier"],"A2","maison","nom"),("mirror",["miroir"],"A2","maison","nom"),
("towel",["serviette"],"A2","maison","nom"),("blanket",["couverture"],"B1","maison","nom"),
("shelf",["étagère"],"B1","maison","nom"),("drawer",["tiroir"],"B1","maison","nom"),
("rent",["loyer"],"B1","maison","nom"),("flat",["appartement"],"A2","maison","nom"),
("building",["immeuble"],"A2","maison","nom"),("ceiling",["plafond"],"B1","maison","nom"),
("cupboard",["armoire"],"A2","maison","nom"),("fridge",["réfrigérateur"],"A2","maison","nom"),
# ---------------- corps & santé ----------------
("ear",["oreille"],"A1","corps-sante","nom"),("leg",["jambe"],"A1","corps-sante","nom"),
("finger",["doigt"],"A2","corps-sante","nom"),("knee",["genou"],"A2","corps-sante","nom"),
("shoulder",["épaule"],"A2","corps-sante","nom"),("throat",["gorge"],"B1","corps-sante","nom"),
("skin",["peau"],"B1","corps-sante","nom"),("blood",["sang"],"B1","corps-sante","nom"),
("bone",["os"],"B1","corps-sante","nom"),("tooth",["dent"],"A2","corps-sante","nom"),
("fever",["fièvre"],"A2","corps-sante","nom"),("cough",["toux"],"B1","corps-sante","nom"),
("wound",["blessure"],"B1","corps-sante","nom"),("nurse",["infirmier"],"A2","corps-sante","nom"),
("pill",["comprimé"],"B1","corps-sante","nom"),("hospital",["hôpital"],"A2","corps-sante","nom"),
# ---------------- vêtements ----------------
("trousers",["pantalon"],"A1","vetements","nom"),("shirt",["chemise"],"A1","vetements","nom"),
("coat",["manteau"],"A1","vetements","nom"),("skirt",["jupe"],"A2","vetements","nom"),
("jumper",["pull"],"A2","vetements","nom"),("sock",["chaussette"],"A2","vetements","nom"),
("hat",["chapeau"],"A2","vetements","nom"),("dress",["robe"],"A2","vetements","nom"),
("belt",["ceinture"],"B1","vetements","nom"),("glove",["gant"],"B1","vetements","nom"),
("scarf",["écharpe"],"B1","vetements","nom"),("jacket",["veste"],"A2","vetements","nom"),
("boot",["botte"],"B1","vetements","nom"),("pocket",["poche"],"A2","vetements","nom"),
# ---------------- ville ----------------
("village",["village"],"A2","ville","nom"),("shop",["magasin"],"A1","ville","nom"),
("market",["marché"],"A2","ville","nom"),("street",["rue"],"A1","ville","nom"),
("bridge",["pont"],"A2","ville","nom"),("church",["église"],"A2","ville","nom"),
("castle",["château"],"B1","ville","nom"),("museum",["musée"],"A2","ville","nom"),
("library",["bibliothèque"],"A2","ville","nom"),("park",["parc"],"A1","ville","nom"),
("pharmacy",["pharmacie"],"A2","ville","nom"),("bakery",["boulangerie"],"A2","ville","nom"),
("town hall",["mairie"],"B1","ville","nom"),("neighbourhood",["quartier"],"B1","ville","nom"),
("crossroads",["carrefour"],"B1","ville","nom"),("pavement",["trottoir"],"B1","ville","nom"),
# ---------------- transports & voyage ----------------
("car",["voiture"],"A1","transports-voyage","nom"),("plane",["avion"],"A1","transports-voyage","nom"),
("bicycle",["vélo"],"A1","transports-voyage","nom"),("boat",["bateau"],"A2","transports-voyage","nom"),
("road",["route"],"A2","transports-voyage","nom"),("airport",["aéroport"],"A2","transports-voyage","nom"),
("luggage",["bagages"],"A2","transports-voyage","nom"),("suitcase",["valise"],"A2","transports-voyage","nom"),
("driver",["conducteur"],"A2","transports-voyage","nom"),("passenger",["passager"],"B1","transports-voyage","nom"),
("delay",["retard"],"B1","transports-voyage","nom"),("harbour",["port"],"B1","transports-voyage","nom"),
("platform",["quai"],"B1","transports-voyage","nom"),("fare",["tarif"],"B1","transports-voyage","nom"),
# ---------------- météo ----------------
("rain",["pluie"],"A1","temps-meteo","nom"),("snow",["neige"],"A1","temps-meteo","nom"),
("wind",["vent"],"A1","temps-meteo","nom"),("cloud",["nuage"],"A2","temps-meteo","nom"),
("storm",["orage"],"A2","temps-meteo","nom"),("fog",["brouillard"],"B1","temps-meteo","nom"),
("heat",["chaleur"],"B1","temps-meteo","nom"),("sky",["ciel"],"A2","temps-meteo","nom"),
("season",["saison"],"A2","temps-meteo","nom"),("spring",["printemps"],"A2","temps-meteo","nom"),
("summer",["été"],"A1","temps-meteo","nom"),("autumn",["automne"],"A2","temps-meteo","nom"),
("winter",["hiver"],"A1","temps-meteo","nom"),("shower",["averse"],"B1","temps-meteo","nom"),
# ---------------- nature & environnement ----------------
("tree",["arbre"],"A1","nature-environnement","nom"),("flower",["fleur"],"A1","nature-environnement","nom"),
("grass",["herbe"],"A2","nature-environnement","nom"),("forest",["forêt"],"A2","nature-environnement","nom"),
("mountain",["montagne"],"A2","nature-environnement","nom"),("river",["rivière"],"A2","nature-environnement","nom"),
("sea",["mer"],"A1","nature-environnement","nom"),("lake",["lac"],"A2","nature-environnement","nom"),
("beach",["plage"],"A2","nature-environnement","nom"),("island",["île"],"B1","nature-environnement","nom"),
("stone",["pierre"],"B1","nature-environnement","nom"),("sand",["sable"],"B1","nature-environnement","nom"),
("animal",["animal"],"A1","nature-environnement","nom"),("bird",["oiseau"],"A1","nature-environnement","nom"),
("dog",["chien"],"A1","nature-environnement","nom"),("cat",["chat"],"A1","nature-environnement","nom"),
("horse",["cheval"],"A2","nature-environnement","nom"),("cow",["vache"],"A2","nature-environnement","nom"),
# ---------------- loisirs & sport ----------------
("team",["équipe"],"A2","loisirs-sport","nom"),("player",["joueur"],"A2","loisirs-sport","nom"),
("ball",["ballon"],"A1","loisirs-sport","nom"),("swimming",["natation"],"A2","loisirs-sport","nom"),
("walk",["promenade"],"A2","loisirs-sport","nom"),("holiday",["vacances"],"A1","loisirs-sport","nom"),
("party",["fête"],"A2","loisirs-sport","nom"),("song",["chanson"],"A1","loisirs-sport","nom"),
("dance",["danse"],"A2","loisirs-sport","nom"),("hobby",["passe-temps"],"A2","loisirs-sport","nom"),
("camera",["appareil photo"],"A2","loisirs-sport","nom"),("drawing",["dessin"],"B1","loisirs-sport","nom"),
("audience",["public"],"B1","loisirs-sport","nom"),("stadium",["stade"],"B1","loisirs-sport","nom"),
# ---------------- travail & études ----------------
("school",["école"],"A1","travail-etudes","nom"),("teacher",["enseignant"],"A1","travail-etudes","nom"),
("pupil",["élève"],"A1","travail-etudes","nom"),("student",["étudiant"],"A1","travail-etudes","nom"),
("lesson",["leçon"],"A1","travail-etudes","nom"),("homework",["devoirs"],"A2","travail-etudes","nom"),
("exam",["examen"],"A2","travail-etudes","nom"),("classroom",["salle de classe"],"A2","travail-etudes","nom"),
("degree",["diplôme"],"B1","travail-etudes","nom"),("factory",["usine"],"B1","travail-etudes","nom"),
("worker",["ouvrier"],"B1","travail-etudes","nom"),("wage",["salaire"],"B1","travail-etudes","nom"),
("deadline",["échéance"],"B2","travail-etudes","nom"),("workshop",["atelier"],"B1","travail-etudes","nom"),
# ---------------- sentiments ----------------
("joy",["joie"],"B1","sentiments","nom"),("sadness",["tristesse"],"B1","sentiments","nom"),
("fear",["peur"],"A2","sentiments","nom"),("anger",["colère"],"B1","sentiments","nom"),
("hope",["espoir"],"B1","sentiments","nom"),("love",["amour"],"A2","sentiments","nom"),
("shame",["honte"],"B2","sentiments","nom"),("pride",["fierté"],"B2","sentiments","nom"),
("boredom",["ennui"],"B2","sentiments","nom"),("jealousy",["jalousie"],"B2","sentiments","nom"),
("trust",["confiance"],"B1","sentiments","nom"),("relief",["soulagement"],"B2","sentiments","nom"),
# ---------------- communication ----------------
("word",["mot"],"A1","communication","nom"),("sentence",["phrase"],"A2","communication","nom"),
("answer",["réponse"],"A1","communication","nom"),("message",["message"],"A1","communication","nom"),
("newspaper",["journal"],"A2","communication","nom"),("advertisement",["publicité"],"B1","communication","nom"),
("meaning",["signification"],"B1","communication","nom"),("mistake",["erreur"],"A2","communication","nom"),
("story",["histoire"],"A2","communication","nom"),("speech",["discours"],"B2","communication","nom"),
("silence",["silence"],"B1","communication","nom"),("rumour",["rumeur"],"B2","communication","nom"),
# ---------------- verbes ----------------
("to walk",["marcher"],"A1","verbes","verbe"),("to run",["courir"],"A1","verbes","verbe"),
("to swim",["nager"],"A2","verbes","verbe"),("to sleep",["dormir"],"A1","verbes","verbe"),
("to buy",["acheter"],"A1","verbes","verbe"),("to sell",["vendre"],"A2","verbes","verbe"),
("to pay",["payer"],"A2","verbes","verbe"),("to cook",["cuisiner"],"A2","verbes","verbe"),
("to wash",["laver"],"A2","verbes","verbe"),("to clean",["nettoyer"],"A2","verbes","verbe"),
("to open",["ouvrir"],"A1","verbes","verbe"),("to close",["fermer"],"A1","verbes","verbe"),
("to build",["construire"],"B1","verbes","verbe"),("to repair",["réparer"],"B1","verbes","verbe"),
("to throw",["jeter"],"B1","verbes","verbe"),("to catch",["attraper"],"B1","verbes","verbe"),
("to push",["pousser"],"B1","verbes","verbe"),("to pull",["tirer"],"B1","verbes","verbe"),
("to lend",["prêter"],"B1","verbes","verbe"),("to borrow",["emprunter"],"B1","verbes","verbe"),
("to choose",["choisir"],"A2","verbes","verbe"),("to decide",["décider"],"B1","verbes","verbe"),
("to try",["essayer"],"A2","verbes","verbe"),("to win",["gagner"],"A2","verbes","verbe"),
("to lose",["perdre"],"A2","verbes","verbe"),("to forget",["oublier"],"A2","verbes","verbe"),
("to laugh",["rire"],"A2","verbes","verbe"),("to cry",["pleurer"],"A2","verbes","verbe"),
("to sing",["chanter"],"A1","verbes","verbe"),("to dance",["danser"],"A1","verbes","verbe"),
("to draw",["dessiner"],"A2","verbes","verbe"),("to teach",["enseigner"],"B1","verbes","verbe"),
("to explain",["expliquer"],"B1","verbes","verbe"),("to listen",["écouter"],"A1","verbes","verbe"),
("to travel",["voyager"],"A2","verbes","verbe"),("to arrive",["arriver"],"A2","verbes","verbe"),
("to wait",["attendre"],"A2","verbes","verbe"),("to help",["aider"],"A1","verbes","verbe"),
("to hope",["espérer"],"B1","verbes","verbe"),("to forbid",["interdire"],"B2","verbes","verbe"),
("to grow",["grandir"],"B1","verbes","verbe"),("to send",["envoyer"],"A2","verbes","verbe"),
("to receive",["recevoir"],"B1","verbes","verbe"),("to carry",["porter"],"B1","verbes","verbe"),
# ---------------- adjectifs ----------------
("big",["grand"],"A1","adjectifs","adjectif"),("small",["petit"],"A1","adjectifs","adjectif"),
("new",["nouveau"],"A1","adjectifs","adjectif"),("old",["vieux"],"A1","adjectifs","adjectif"),
("good",["bon"],"A1","adjectifs","adjectif"),("bad",["mauvais"],"A1","adjectifs","adjectif"),
("beautiful",["beau"],"A1","adjectifs","adjectif"),("ugly",["laid"],"A2","adjectifs","adjectif"),
("fast",["rapide"],"A1","adjectifs","adjectif"),("slow",["lent"],"A2","adjectifs","adjectif"),
("hot",["chaud"],"A1","adjectifs","adjectif"),("cold",["froid"],"A1","adjectifs","adjectif"),
("expensive",["cher"],"A2","adjectifs","adjectif"),("cheap",["bon marché"],"A2","adjectifs","adjectif"),
("easy",["facile"],"A1","adjectifs","adjectif"),("difficult",["difficile"],"A1","adjectifs","adjectif"),
("strong",["fort"],"A2","adjectifs","adjectif"),("weak",["faible"],"B1","adjectifs","adjectif"),
("high",["haut"],"A2","adjectifs","adjectif"),("low",["bas"],"A2","adjectifs","adjectif"),
("full",["plein"],"A2","adjectifs","adjectif"),("empty",["vide"],"A2","adjectifs","adjectif"),
("clean",["propre"],"A2","adjectifs","adjectif"),("dirty",["sale"],"A2","adjectifs","adjectif"),
("dangerous",["dangereux"],"B1","adjectifs","adjectif"),("safe",["sûr"],"B1","adjectifs","adjectif"),
("heavy",["lourd"],"A2","adjectifs","adjectif"),("light",["léger"],"A2","adjectifs","adjectif"),
("wide",["large"],"B1","adjectifs","adjectif"),("narrow",["étroit"],"B1","adjectifs","adjectif"),
("deep",["profond"],"B1","adjectifs","adjectif"),("loud",["bruyant"],"B1","adjectifs","adjectif"),
("tired",["fatigué"],"A2","adjectifs","adjectif"),("hungry",["affamé"],"A2","adjectifs","adjectif"),
("thirsty",["assoiffé"],"A2","adjectifs","adjectif"),("happy",["heureux"],"A1","adjectifs","adjectif"),
("sad",["triste"],"A1","adjectifs","adjectif"),("ready",["prêt"],"A2","adjectifs","adjectif"),
("busy",["occupé"],"A2","adjectifs","adjectif"),("useful",["utile"],"A2","adjectifs","adjectif"),
("useless",["inutile"],"B1","adjectifs","adjectif"),("young",["jeune"],"A1","adjectifs","adjectif"),
# ---------------- mots-outils ----------------
("but",["mais"],"A1","mots-outils","mot-outil"),("because",["parce que"],"A1","mots-outils","mot-outil"),
("also",["aussi"],"A1","mots-outils","mot-outil"),("already",["déjà"],"A2","mots-outils","mot-outil"),
("here",["ici"],"A1","mots-outils","mot-outil"),("there",["là"],"A1","mots-outils","mot-outil"),
("why",["pourquoi"],"A1","mots-outils","mot-outil"),("how",["comment"],"A1","mots-outils","mot-outil"),
("when",["quand"],"A1","mots-outils","mot-outil"),("where",["où"],"A1","mots-outils","mot-outil"),
("maybe",["peut-être"],"A2","mots-outils","mot-outil"),("almost",["presque"],"A2","mots-outils","mot-outil"),
("enough",["assez"],"A2","mots-outils","mot-outil"),("together",["ensemble"],"A2","mots-outils","mot-outil"),
("against",["contre"],"A2","mots-outils","mot-outil"),("without",["sans"],"A1","mots-outils","mot-outil"),
("between",["entre"],"A2","mots-outils","mot-outil"),("during",["pendant"],"A2","mots-outils","mot-outil"),
("before",["avant"],"A1","mots-outils","mot-outil"),("after",["après"],"A1","mots-outils","mot-outil"),
("always",["toujours"],"A1","mots-outils","mot-outil"),("never",["jamais"],"A1","mots-outils","mot-outil"),
("often",["souvent"],"A2","mots-outils","mot-outil"),("sometimes",["parfois"],"A2","mots-outils","mot-outil"),
("everywhere",["partout"],"B1","mots-outils","mot-outil"),("nothing",["rien"],"A1","mots-outils","mot-outil"),
("everything",["tout"],"A1","mots-outils","mot-outil"),("someone",["quelqu'un"],"A2","mots-outils","mot-outil"),
("nobody",["personne (aucun)"],"A2","mots-outils","mot-outil"),
# ---------------- société & actualité ----------------
("government",["gouvernement"],"B1","societe-actualite","nom"),("law",["loi"],"B1","societe-actualite","nom"),
("election",["élection"],"B2","societe-actualite","nom"),("tax",["impôt"],"B2","societe-actualite","nom"),
("population",["population"],"B2","societe-actualite","nom"),("freedom",["liberté"],"B1","societe-actualite","nom"),
("safety",["sécurité"],"B1","societe-actualite","nom"),("war",["guerre"],"B1","societe-actualite","nom"),
("peace",["paix"],"B1","societe-actualite","nom"),("citizen",["citoyen"],"B2","societe-actualite","nom"),
("court",["tribunal"],"B2","societe-actualite","nom"),("prison",["prison"],"B2","societe-actualite","nom"),
("strike",["grève"],"B2","societe-actualite","nom"),("survey",["sondage"],"B2","societe-actualite","nom"),
]
