# -*- coding: utf-8 -*-
"""Extension de la banque allemande.

CES MOTS NE VIENNENT PAS DES LEXIQUES DU SITE : ils sont ajoutés pour le volume
et portent tous source="non-verifie". Même règle que pour les autres langues :
vocabulaire courant, concret, peu ambigu. Les mots à double sens (die Decke =
couverture/plafond, das Gericht = tribunal/plat, die Tasche = poche/sac,
der Hals = cou/gorge) sont écartés exprès.
Conventions : nom précédé de son article (c'est le genre qu'il faut retenir),
traduction française avec article, verbes à l'infinitif. Le marqueur de pluriel
des lexiques n'est PAS repris ici : il n'a pas été vérifié, on ne l'invente pas.
"""
# (mot, [traductions], niveau, categorie, classe)
EXT = [
# ---------------- famille & personnes ----------------
("der Onkel",["l'oncle"],"A2","famille","nom"),("die Tante",["la tante"],"A2","famille","nom"),
("der Cousin",["le cousin"],"A2","famille","nom"),("die Cousine",["la cousine"],"A2","famille","nom"),
("der Ehemann",["le mari"],"A2","famille","nom"),("die Ehefrau",["l'épouse"],"A2","famille","nom"),
("der Nachbar",["le voisin"],"A2","famille","nom"),("der Kollege",["le collègue"],"A2","famille","nom"),
("der Neffe",["le neveu"],"B1","famille","nom"),("die Nichte",["la nièce"],"B1","famille","nom"),
("der Junge",["le garçon"],"A1","famille","nom"),("das Mädchen",["la fille (jeune)"],"A1","famille","nom"),
("der Erwachsene",["l'adulte"],"B1","famille","nom"),("das Paar",["le couple"],"A2","famille","nom"),
("der Sohn",["le fils"],"A1","famille","nom"),("die Tochter",["la fille (enfant de)"],"A1","famille","nom"),
# ---------------- nourriture ----------------
("der Reis",["le riz"],"A2","nourriture","nom"),("das Salz",["le sel"],"A1","nourriture","nom"),
("die Butter",["le beurre"],"A1","nourriture","nom"),("das Öl",["l'huile"],"A2","nourriture","nom"),
("der Salat",["la salade"],"A2","nourriture","nom"),("das Hähnchen",["le poulet"],"A2","nourriture","nom"),
("der Tee",["le thé"],"A1","nourriture","nom"),("der Saft",["le jus"],"A1","nourriture","nom"),
("der Wein",["le vin"],"A2","nourriture","nom"),("das Bier",["la bière"],"A2","nourriture","nom"),
("der Kuchen",["le gâteau"],"A2","nourriture","nom"),("die Schokolade",["le chocolat"],"A1","nourriture","nom"),
("die Kartoffel",["la pomme de terre"],"A1","nourriture","nom"),("das Gemüse",["le légume"],"A1","nourriture","nom"),
("das Frühstück",["le petit-déjeuner"],"A2","nourriture","nom"),("das Mittagessen",["le déjeuner"],"A2","nourriture","nom"),
("das Abendessen",["le dîner"],"A2","nourriture","nom"),("die Mahlzeit",["le repas"],"A2","nourriture","nom"),
("der Teller",["l'assiette"],"A2","nourriture","nom"),("die Gabel",["la fourchette"],"A2","nourriture","nom"),
("das Messer",["le couteau"],"A2","nourriture","nom"),("der Löffel",["la cuillère"],"A2","nourriture","nom"),
("die Flasche",["la bouteille"],"A1","nourriture","nom"),("der Hunger",["la faim"],"A2","nourriture","nom"),
("der Durst",["la soif"],"A2","nourriture","nom"),("das Fleisch",["la viande"],"A1","nourriture","nom"),
# ---------------- maison ----------------
("das Haus",["la maison"],"A1","maison","nom"),("die Tür",["la porte"],"A1","maison","nom"),
("das Fenster",["la fenêtre"],"A1","maison","nom"),("der Tisch",["la table"],"A1","maison","nom"),
("der Stuhl",["la chaise"],"A1","maison","nom"),("das Bett",["le lit"],"A1","maison","nom"),
("die Küche",["la cuisine (pièce)"],"A1","maison","nom"),("das Schlafzimmer",["la chambre"],"A1","maison","nom"),
("der Garten",["le jardin"],"A2","maison","nom"),("die Wand",["le mur"],"A2","maison","nom"),
("das Dach",["le toit"],"A2","maison","nom"),("die Treppe",["l'escalier"],"A2","maison","nom"),
("der Schlüssel",["la clé"],"A1","maison","nom"),("die Lampe",["la lampe"],"A1","maison","nom"),
("der Spiegel",["le miroir"],"A2","maison","nom"),("das Handtuch",["la serviette"],"A2","maison","nom"),
("die Schublade",["le tiroir"],"B1","maison","nom"),("die Miete",["le loyer"],"B1","maison","nom"),
("die Wohnung",["l'appartement"],"A2","maison","nom"),("das Gebäude",["l'immeuble"],"A2","maison","nom"),
("der Schrank",["l'armoire"],"A2","maison","nom"),("der Kühlschrank",["le réfrigérateur"],"A2","maison","nom"),
("der Boden",["le sol"],"A2","maison","nom"),
# ---------------- corps & santé ----------------
("der Kopf",["la tête"],"A1","corps-sante","nom"),("die Hand",["la main"],"A1","corps-sante","nom"),
("der Fuß",["le pied"],"A1","corps-sante","nom"),("das Auge",["l'œil"],"A1","corps-sante","nom"),
("der Mund",["la bouche"],"A1","corps-sante","nom"),("die Nase",["le nez"],"A1","corps-sante","nom"),
("das Ohr",["l'oreille"],"A1","corps-sante","nom"),("der Arm",["le bras"],"A1","corps-sante","nom"),
("das Bein",["la jambe"],"A1","corps-sante","nom"),("das Herz",["le cœur"],"A1","corps-sante","nom"),
("der Rücken",["le dos"],"A2","corps-sante","nom"),("der Zahn",["la dent"],"A2","corps-sante","nom"),
("die Haut",["la peau"],"B1","corps-sante","nom"),("das Blut",["le sang"],"B1","corps-sante","nom"),
("der Knochen",["l'os"],"B1","corps-sante","nom"),("der Finger",["le doigt"],"A2","corps-sante","nom"),
("das Knie",["le genou"],"A2","corps-sante","nom"),("die Schulter",["l'épaule"],"A2","corps-sante","nom"),
("das Fieber",["la fièvre"],"A2","corps-sante","nom"),("der Husten",["la toux"],"B1","corps-sante","nom"),
("die Wunde",["la blessure"],"B1","corps-sante","nom"),("die Krankenschwester",["l'infirmière"],"A2","corps-sante","nom"),
("die Tablette",["le comprimé"],"B1","corps-sante","nom"),("das Krankenhaus",["l'hôpital"],"A2","corps-sante","nom"),
# ---------------- vêtements ----------------
("die Hose",["le pantalon"],"A1","vetements","nom"),("das Hemd",["la chemise"],"A1","vetements","nom"),
("der Mantel",["le manteau"],"A1","vetements","nom"),("der Rock",["la jupe"],"A2","vetements","nom"),
("der Pullover",["le pull"],"A2","vetements","nom"),("die Socke",["la chaussette"],"A2","vetements","nom"),
("der Hut",["le chapeau"],"A2","vetements","nom"),("das Kleid",["la robe"],"A2","vetements","nom"),
("der Gürtel",["la ceinture"],"B1","vetements","nom"),("der Handschuh",["le gant"],"B1","vetements","nom"),
("der Schal",["l'écharpe"],"B1","vetements","nom"),("die Jacke",["la veste"],"A2","vetements","nom"),
("der Stiefel",["la botte"],"B1","vetements","nom"),("der Schuh",["la chaussure"],"A1","vetements","nom"),
# ---------------- ville ----------------
("das Dorf",["le village"],"A2","ville","nom"),("das Geschäft",["le magasin"],"A1","ville","nom"),
("der Markt",["le marché"],"A2","ville","nom"),("die Straße",["la rue"],"A1","ville","nom"),
("die Brücke",["le pont"],"A2","ville","nom"),("die Kirche",["l'église"],"A2","ville","nom"),
("das Schloss",["le château"],"B1","ville","nom"),("das Museum",["le musée"],"A2","ville","nom"),
("die Bibliothek",["la bibliothèque"],"A2","ville","nom"),("der Park",["le parc"],"A1","ville","nom"),
("die Apotheke",["la pharmacie"],"A2","ville","nom"),("die Bäckerei",["la boulangerie"],"A2","ville","nom"),
("das Rathaus",["la mairie"],"B1","ville","nom"),("das Viertel",["le quartier"],"B1","ville","nom"),
("der Bürgersteig",["le trottoir"],"B1","ville","nom"),("der Platz",["la place"],"A2","ville","nom"),
# ---------------- transports & voyage ----------------
("das Auto",["la voiture"],"A1","transports-voyage","nom"),("das Flugzeug",["l'avion"],"A1","transports-voyage","nom"),
("das Fahrrad",["le vélo"],"A1","transports-voyage","nom"),("das Schiff",["le bateau"],"A2","transports-voyage","nom"),
("die Autobahn",["l'autoroute"],"B1","transports-voyage","nom"),("der Flughafen",["l'aéroport"],"A2","transports-voyage","nom"),
("das Gepäck",["les bagages"],"A2","transports-voyage","nom"),("der Koffer",["la valise"],"A2","transports-voyage","nom"),
("der Fahrer",["le conducteur"],"A2","transports-voyage","nom"),("der Fahrgast",["le passager"],"B1","transports-voyage","nom"),
("die Verspätung",["le retard"],"B1","transports-voyage","nom"),("der Hafen",["le port"],"B1","transports-voyage","nom"),
("der Bahnsteig",["le quai"],"B1","transports-voyage","nom"),("der Zug",["le train"],"A1","transports-voyage","nom"),
("der Bahnhof",["la gare"],"A1","transports-voyage","nom"),("die Grenze",["la frontière"],"B1","transports-voyage","nom"),
# ---------------- météo ----------------
("der Regen",["la pluie"],"A1","temps-meteo","nom"),("der Schnee",["la neige"],"A1","temps-meteo","nom"),
("der Wind",["le vent"],"A1","temps-meteo","nom"),("die Wolke",["le nuage"],"A2","temps-meteo","nom"),
("das Gewitter",["l'orage"],"A2","temps-meteo","nom"),("der Nebel",["le brouillard"],"B1","temps-meteo","nom"),
("die Hitze",["la chaleur"],"B1","temps-meteo","nom"),("der Himmel",["le ciel"],"A2","temps-meteo","nom"),
("die Jahreszeit",["la saison"],"A2","temps-meteo","nom"),("der Frühling",["le printemps"],"A2","temps-meteo","nom"),
("der Sommer",["l'été"],"A1","temps-meteo","nom"),("der Herbst",["l'automne"],"A2","temps-meteo","nom"),
("der Winter",["l'hiver"],"A1","temps-meteo","nom"),("die Sonne",["le soleil"],"A1","temps-meteo","nom"),
# ---------------- nature & environnement ----------------
("der Baum",["l'arbre"],"A1","nature-environnement","nom"),("die Blume",["la fleur"],"A1","nature-environnement","nom"),
("das Gras",["l'herbe"],"A2","nature-environnement","nom"),("der Wald",["la forêt"],"A2","nature-environnement","nom"),
("der Berg",["la montagne"],"A2","nature-environnement","nom"),("der Fluss",["la rivière"],"A2","nature-environnement","nom"),
("das Meer",["la mer"],"A1","nature-environnement","nom"),("der See",["le lac"],"A2","nature-environnement","nom"),
("der Strand",["la plage"],"A2","nature-environnement","nom"),("die Insel",["l'île"],"B1","nature-environnement","nom"),
("der Stein",["la pierre"],"B1","nature-environnement","nom"),("der Sand",["le sable"],"B1","nature-environnement","nom"),
("das Tier",["l'animal"],"A1","nature-environnement","nom"),("der Vogel",["l'oiseau"],"A1","nature-environnement","nom"),
("der Hund",["le chien"],"A1","nature-environnement","nom"),("die Katze",["le chat"],"A1","nature-environnement","nom"),
("das Pferd",["le cheval"],"A2","nature-environnement","nom"),("die Kuh",["la vache"],"A2","nature-environnement","nom"),
# ---------------- loisirs & sport ----------------
("die Mannschaft",["l'équipe"],"A2","loisirs-sport","nom"),("der Spieler",["le joueur"],"A2","loisirs-sport","nom"),
("der Ball",["le ballon"],"A1","loisirs-sport","nom"),("das Schwimmen",["la natation"],"A2","loisirs-sport","nom"),
("der Spaziergang",["la promenade"],"A2","loisirs-sport","nom"),("die Ferien",["les vacances"],"A1","loisirs-sport","nom"),
("das Fest",["la fête"],"A2","loisirs-sport","nom"),("das Lied",["la chanson"],"A1","loisirs-sport","nom"),
("der Tanz",["la danse"],"A2","loisirs-sport","nom"),("die Zeichnung",["le dessin"],"B1","loisirs-sport","nom"),
("das Publikum",["le public"],"B1","loisirs-sport","nom"),("das Stadion",["le stade"],"B1","loisirs-sport","nom"),
("der Film",["le film"],"A1","loisirs-sport","nom"),("das Buch",["le livre"],"A1","loisirs-sport","nom"),
# ---------------- travail & études ----------------
("die Schule",["l'école"],"A1","travail-etudes","nom"),("der Lehrer",["l'enseignant"],"A1","travail-etudes","nom"),
("der Schüler",["l'élève"],"A1","travail-etudes","nom"),("der Student",["l'étudiant"],"A1","travail-etudes","nom"),
("die Lektion",["la leçon"],"A1","travail-etudes","nom"),("die Hausaufgaben",["les devoirs"],"A2","travail-etudes","nom"),
("die Prüfung",["l'examen"],"A2","travail-etudes","nom"),("das Klassenzimmer",["la salle de classe"],"A2","travail-etudes","nom"),
("der Abschluss",["le diplôme"],"B1","travail-etudes","nom"),("die Fabrik",["l'usine"],"B1","travail-etudes","nom"),
("der Arbeiter",["l'ouvrier"],"B1","travail-etudes","nom"),("der Lohn",["le salaire"],"B1","travail-etudes","nom"),
("die Frist",["l'échéance"],"B2","travail-etudes","nom"),("die Werkstatt",["l'atelier"],"B1","travail-etudes","nom"),
# ---------------- sentiments ----------------
("die Freude",["la joie"],"B1","sentiments","nom"),("die Trauer",["la tristesse"],"B1","sentiments","nom"),
("die Angst",["la peur"],"A2","sentiments","nom"),("die Wut",["la colère"],"B1","sentiments","nom"),
("die Hoffnung",["l'espoir"],"B1","sentiments","nom"),("die Liebe",["l'amour"],"A2","sentiments","nom"),
("die Scham",["la honte"],"B2","sentiments","nom"),("der Stolz",["la fierté"],"B2","sentiments","nom"),
("die Langeweile",["l'ennui"],"B2","sentiments","nom"),("die Eifersucht",["la jalousie"],"B2","sentiments","nom"),
("das Vertrauen",["la confiance"],"B1","sentiments","nom"),("die Erleichterung",["le soulagement"],"B2","sentiments","nom"),
# ---------------- communication ----------------
("das Wort",["le mot"],"A1","communication","nom"),("der Satz",["la phrase"],"A2","communication","nom"),
("die Antwort",["la réponse"],"A1","communication","nom"),("die Nachricht",["le message"],"A1","communication","nom"),
("die Zeitung",["le journal"],"A2","communication","nom"),("die Werbung",["la publicité"],"B1","communication","nom"),
("die Bedeutung",["la signification"],"B1","communication","nom"),("der Fehler",["l'erreur"],"A2","communication","nom"),
("die Geschichte",["l'histoire"],"A2","communication","nom"),("die Rede",["le discours"],"B2","communication","nom"),
("die Stille",["le silence"],"B1","communication","nom"),("das Gerücht",["la rumeur"],"B2","communication","nom"),
# ---------------- verbes ----------------
("rennen",["courir"],"A2","verbes","verbe"),("schwimmen",["nager"],"A2","verbes","verbe"),
("schlafen",["dormir"],"A1","verbes","verbe"),("kaufen",["acheter"],"A1","verbes","verbe"),
("verkaufen",["vendre"],"A2","verbes","verbe"),("bezahlen",["payer"],"A2","verbes","verbe"),
("kochen",["cuisiner"],"A2","verbes","verbe"),("waschen",["laver"],"A2","verbes","verbe"),
("putzen",["nettoyer"],"A2","verbes","verbe"),("öffnen",["ouvrir"],"A1","verbes","verbe"),
("schließen",["fermer"],"A1","verbes","verbe"),("bauen",["construire"],"B1","verbes","verbe"),
("reparieren",["réparer"],"B1","verbes","verbe"),("werfen",["jeter"],"B1","verbes","verbe"),
("schieben",["pousser"],"B1","verbes","verbe"),("ziehen",["tirer"],"B1","verbes","verbe"),
("leihen",["prêter"],"B1","verbes","verbe"),("wählen",["choisir"],"A2","verbes","verbe"),
("entscheiden",["décider"],"B1","verbes","verbe"),("versuchen",["essayer"],"A2","verbes","verbe"),
("gewinnen",["gagner"],"A2","verbes","verbe"),("verlieren",["perdre"],"A2","verbes","verbe"),
("vergessen",["oublier"],"A2","verbes","verbe"),("lachen",["rire"],"A2","verbes","verbe"),
("weinen",["pleurer"],"A2","verbes","verbe"),("singen",["chanter"],"A1","verbes","verbe"),
("tanzen",["danser"],"A1","verbes","verbe"),("zeichnen",["dessiner"],"A2","verbes","verbe"),
("unterrichten",["enseigner"],"B1","verbes","verbe"),("erklären",["expliquer"],"B1","verbes","verbe"),
("zuhören",["écouter"],"A1","verbes","verbe"),("reisen",["voyager"],"A2","verbes","verbe"),
("ankommen",["arriver"],"A2","verbes","verbe"),("warten",["attendre"],"A2","verbes","verbe"),
("helfen",["aider"],"A1","verbes","verbe"),("verbieten",["interdire"],"B2","verbes","verbe"),
("wachsen",["grandir"],"B1","verbes","verbe"),("schicken",["envoyer"],"A2","verbes","verbe"),
("bekommen",["recevoir"],"B1","verbes","verbe"),("tragen",["porter"],"B1","verbes","verbe"),
("lesen",["lire"],"A1","verbes","verbe"),("schreiben",["écrire"],"A1","verbes","verbe"),
("arbeiten",["travailler"],"A1","verbes","verbe"),("lernen",["apprendre"],"A1","verbes","verbe"),
# ---------------- adjectifs ----------------
("groß",["grand"],"A1","adjectifs","adjectif"),("klein",["petit"],"A1","adjectifs","adjectif"),
("neu",["nouveau"],"A1","adjectifs","adjectif"),("alt",["vieux"],"A1","adjectifs","adjectif"),
("gut",["bon"],"A1","adjectifs","adjectif"),("schlecht",["mauvais"],"A1","adjectifs","adjectif"),
("schön",["beau"],"A1","adjectifs","adjectif"),("hässlich",["laid"],"A2","adjectifs","adjectif"),
("schnell",["rapide"],"A1","adjectifs","adjectif"),("langsam",["lent"],"A2","adjectifs","adjectif"),
("heiß",["chaud"],"A1","adjectifs","adjectif"),("kalt",["froid"],"A1","adjectifs","adjectif"),
("teuer",["cher"],"A2","adjectifs","adjectif"),("billig",["bon marché"],"A2","adjectifs","adjectif"),
("einfach",["facile"],"A1","adjectifs","adjectif"),("schwierig",["difficile"],"A1","adjectifs","adjectif"),
("stark",["fort"],"A2","adjectifs","adjectif"),("schwach",["faible"],"B1","adjectifs","adjectif"),
("hoch",["haut"],"A2","adjectifs","adjectif"),("niedrig",["bas"],"A2","adjectifs","adjectif"),
("voll",["plein"],"A2","adjectifs","adjectif"),("leer",["vide"],"A2","adjectifs","adjectif"),
("sauber",["propre"],"A2","adjectifs","adjectif"),("schmutzig",["sale"],"A2","adjectifs","adjectif"),
("gefährlich",["dangereux"],"B1","adjectifs","adjectif"),("sicher",["sûr"],"B1","adjectifs","adjectif"),
("schwer",["lourd"],"A2","adjectifs","adjectif"),("leicht",["léger"],"A2","adjectifs","adjectif"),
("breit",["large"],"B1","adjectifs","adjectif"),("eng",["étroit"],"B1","adjectifs","adjectif"),
("tief",["profond"],"B1","adjectifs","adjectif"),("laut",["bruyant"],"B1","adjectifs","adjectif"),
("müde",["fatigué"],"A2","adjectifs","adjectif"),("glücklich",["heureux"],"A1","adjectifs","adjectif"),
("traurig",["triste"],"A1","adjectifs","adjectif"),("fertig",["prêt"],"A2","adjectifs","adjectif"),
("beschäftigt",["occupé"],"A2","adjectifs","adjectif"),("nützlich",["utile"],"A2","adjectifs","adjectif"),
("nutzlos",["inutile"],"B1","adjectifs","adjectif"),("jung",["jeune"],"A1","adjectifs","adjectif"),
# ---------------- mots-outils ----------------
("aber",["mais"],"A1","mots-outils","mot-outil"),("weil",["parce que"],"A1","mots-outils","mot-outil"),
("auch",["aussi"],"A1","mots-outils","mot-outil"),("schon",["déjà"],"A2","mots-outils","mot-outil"),
("hier",["ici"],"A1","mots-outils","mot-outil"),("dort",["là-bas"],"A1","mots-outils","mot-outil"),
("warum",["pourquoi"],"A1","mots-outils","mot-outil"),("wie",["comment"],"A1","mots-outils","mot-outil"),
("wann",["quand"],"A1","mots-outils","mot-outil"),("wo",["où"],"A1","mots-outils","mot-outil"),
("vielleicht",["peut-être"],"A2","mots-outils","mot-outil"),("fast",["presque"],"A2","mots-outils","mot-outil"),
("genug",["assez"],"A2","mots-outils","mot-outil"),("zusammen",["ensemble"],"A2","mots-outils","mot-outil"),
("gegen",["contre"],"A2","mots-outils","mot-outil"),("ohne",["sans"],"A1","mots-outils","mot-outil"),
("zwischen",["entre"],"A2","mots-outils","mot-outil"),("während",["pendant"],"A2","mots-outils","mot-outil"),
("vorher",["avant"],"A1","mots-outils","mot-outil"),("nachher",["après"],"A1","mots-outils","mot-outil"),
("immer",["toujours"],"A1","mots-outils","mot-outil"),("nie",["jamais"],"A1","mots-outils","mot-outil"),
("oft",["souvent"],"A2","mots-outils","mot-outil"),("manchmal",["parfois"],"A2","mots-outils","mot-outil"),
("überall",["partout"],"B1","mots-outils","mot-outil"),("nichts",["rien"],"A1","mots-outils","mot-outil"),
("alles",["tout"],"A1","mots-outils","mot-outil"),("jemand",["quelqu'un"],"A2","mots-outils","mot-outil"),
("niemand",["personne (aucun)"],"A2","mots-outils","mot-outil"),("viel",["beaucoup"],"A1","mots-outils","mot-outil"),
# ---------------- société & actualité ----------------
("die Regierung",["le gouvernement"],"B1","societe-actualite","nom"),("das Gesetz",["la loi"],"B1","societe-actualite","nom"),
("die Wahl",["l'élection"],"B2","societe-actualite","nom"),("die Steuer",["l'impôt"],"B2","societe-actualite","nom"),
("die Bevölkerung",["la population"],"B2","societe-actualite","nom"),("die Freiheit",["la liberté"],"B1","societe-actualite","nom"),
("die Sicherheit",["la sécurité"],"B1","societe-actualite","nom"),("der Krieg",["la guerre"],"B1","societe-actualite","nom"),
("der Frieden",["la paix"],"B1","societe-actualite","nom"),("der Bürger",["le citoyen"],"B2","societe-actualite","nom"),
("das Gefängnis",["la prison"],"B2","societe-actualite","nom"),("der Streik",["la grève"],"B2","societe-actualite","nom"),
("die Umfrage",["le sondage"],"B2","societe-actualite","nom"),("die Armut",["la pauvreté"],"B2","societe-actualite","nom"),
("die Arbeitslosigkeit",["le chômage"],"B2","societe-actualite","nom"),
]
