# -*- coding: utf-8 -*-
"""Extension de la banque néerlandaise.
CES MOTS NE VIENNENT PAS DES LEXIQUES DU SITE : ils sont ajoutés pour le volume
et portent tous source="non-verifie". Choix délibéré : uniquement du vocabulaire
courant, concret et peu ambigu, là où la traduction est stable — pour limiter le
risque au maximum. La page affiche le décompte des deux tiers séparément.
"""
# (mot, [traductions], niveau, categorie, classe)
EXT = [
# ---------------- famille & personnes ----------------
("de vader",["le père"],"A1","famille","nom"),("de moeder",["la mère"],"A1","famille","nom"),
("de broer",["le frère"],"A1","famille","nom"),("het kind",["l'enfant"],"A1","famille","nom"),
("de zoon",["le fils"],"A1","famille","nom"),("de dochter",["la fille"],"A1","famille","nom"),
("de oma",["la grand-mère"],"A1","famille","nom"),("de opa",["le grand-père"],"A1","famille","nom"),
("de oom",["l'oncle"],"A2","famille","nom"),("de tante",["la tante"],"A2","famille","nom"),
("de neef",["le cousin"],"A2","famille","nom"),("de nicht",["la cousine"],"A2","famille","nom"),
("de ouders",["les parents"],"A1","famille","nom"),("de man",["l'homme"],"A1","famille","nom"),
("de vrouw",["la femme"],"A1","famille","nom"),("de baby",["le bébé"],"A1","famille","nom"),
("de buurman",["le voisin"],"A2","famille","nom"),("de vriend",["l'ami"],"A1","famille","nom"),
("de vriendin",["l'amie"],"A1","famille","nom"),("de collega",["le collègue"],"A2","famille","nom"),
# ---------------- nourriture ----------------
("de melk",["le lait"],"A1","nourriture","nom"),("het water",["l'eau"],"A1","nourriture","nom"),
("de koffie",["le café"],"A1","nourriture","nom"),("de kaas",["le fromage"],"A1","nourriture","nom"),
("het vlees",["la viande"],"A1","nourriture","nom"),("de vis",["le poisson"],"A1","nourriture","nom"),
("het fruit",["le fruit"],"A1","nourriture","nom"),("de appel",["la pomme"],"A1","nourriture","nom"),
("de aardappel",["la pomme de terre"],"A1","nourriture","nom"),("de groente",["le légume"],"A1","nourriture","nom"),
("het ei",["l'œuf"],"A1","nourriture","nom"),("de boter",["le beurre"],"A1","nourriture","nom"),
("de suiker",["le sucre"],"A1","nourriture","nom"),("het zout",["le sel"],"A1","nourriture","nom"),
("de soep",["la soupe"],"A2","nourriture","nom"),("de rijst",["le riz"],"A2","nourriture","nom"),
("het ontbijt",["le petit-déjeuner"],"A2","nourriture","nom"),("het avondeten",["le dîner"],"A2","nourriture","nom"),
("de honger",["la faim"],"A2","nourriture","nom"),("de dorst",["la soif"],"A2","nourriture","nom"),
# ---------------- maison ----------------
("het huis",["la maison"],"A1","maison","nom"),("de deur",["la porte"],"A1","maison","nom"),
("het raam",["la fenêtre"],"A1","maison","nom"),("de tafel",["la table"],"A1","maison","nom"),
("de stoel",["la chaise"],"A1","maison","nom"),("het bed",["le lit"],"A1","maison","nom"),
("de keuken",["la cuisine"],"A1","maison","nom"),("de kamer",["la chambre"],"A1","maison","nom"),
("de tuin",["le jardin"],"A2","maison","nom"),("de badkamer",["la salle de bains"],"A2","maison","nom"),
("de muur",["le mur"],"A2","maison","nom"),("het dak",["le toit"],"A2","maison","nom"),
("de trap",["l'escalier"],"A2","maison","nom"),("de sleutel",["la clé"],"A1","maison","nom"),
("de lamp",["la lampe"],"A1","maison","nom"),("de kast",["l'armoire"],"A2","maison","nom"),
("het bad",["le bain"],"A2","maison","nom"),("de vloer",["le sol"],"A2","maison","nom"),
("de woning",["le logement"],"B1","maison","nom"),("de huur",["le loyer"],"B1","maison","nom"),
# ---------------- corps & santé ----------------
("het hoofd",["la tête"],"A1","corps-sante","nom"),("de hand",["la main"],"A1","corps-sante","nom"),
("de voet",["le pied"],"A1","corps-sante","nom"),("het oog",["l'œil"],"A1","corps-sante","nom"),
("de mond",["la bouche"],"A1","corps-sante","nom"),("de neus",["le nez"],"A1","corps-sante","nom"),
("de arm",["le bras"],"A1","corps-sante","nom"),("het hart",["le cœur"],"A1","corps-sante","nom"),
("de rug",["le dos"],"A2","corps-sante","nom"),("de buik",["le ventre"],"A2","corps-sante","nom"),
("de dokter",["le médecin"],"A2","corps-sante","nom"),("het ziekenhuis",["l'hôpital"],"A2","corps-sante","nom"),
("de tand",["la dent"],"A2","corps-sante","nom"),("het bloed",["le sang"],"B1","corps-sante","nom"),
("de behandeling",["le traitement"],"B1","corps-sante","nom"),("het onderzoek",["l'examen"],"B1","corps-sante","nom"),
# ---------------- vêtements ----------------
("de broek",["le pantalon"],"A1","vetements","nom"),("het hemd",["la chemise"],"A2","vetements","nom"),
("de jas",["le manteau"],"A1","vetements","nom"),("de rok",["la jupe"],"A2","vetements","nom"),
("de trui",["le pull"],"A1","vetements","nom"),("de sok",["la chaussette"],"A2","vetements","nom"),
("de hoed",["le chapeau"],"A2","vetements","nom"),("de jurk",["la robe"],"A2","vetements","nom"),
("de riem",["la ceinture"],"B1","vetements","nom"),("de handschoen",["le gant"],"B1","vetements","nom"),
# ---------------- ville & orientation ----------------
("de stad",["la ville"],"A1","ville","nom"),("het dorp",["le village"],"A2","ville","nom"),
("de winkel",["le magasin"],"A1","ville","nom"),("de markt",["le marché"],"A2","ville","nom"),
("de kerk",["l'église"],"A2","ville","nom"),("het station",["la gare"],"A1","ville","nom"),
("de brug",["le pont"],"A2","ville","nom"),("het park",["le parc"],"A2","ville","nom"),
("de bibliotheek",["la bibliothèque"],"A2","ville","nom"),("het museum",["le musée"],"A2","ville","nom"),
("links",["à gauche"],"A1","ville","mot-outil"),("rechtdoor",["tout droit"],"A2","ville","mot-outil"),
("de hoek",["le coin"],"B1","ville","nom"),("de wijk",["le quartier"],"B1","ville","nom"),
# ---------------- transports & voyage ----------------
("de trein",["le train"],"A1","transports-voyage","nom"),("de bus",["le bus"],"A1","transports-voyage","nom"),
("de auto",["la voiture"],"A1","transports-voyage","nom"),("de fiets",["le vélo"],"A1","transports-voyage","nom"),
("het vliegtuig",["l'avion"],"A2","transports-voyage","nom"),("de boot",["le bateau"],"A2","transports-voyage","nom"),
("het kaartje",["le billet"],"A2","transports-voyage","nom"),("de koffer",["la valise"],"A2","transports-voyage","nom"),
("de reis",["le voyage"],"A2","transports-voyage","nom"),("de vakantie",["les vacances"],"A2","transports-voyage","nom"),
("de weg",["la route"],"A2","transports-voyage","nom"),("de bestemming",["la destination"],"B1","transports-voyage","nom"),
("de vertraging",["le retard"],"B1","transports-voyage","nom"),("de halte",["l'arrêt"],"B1","transports-voyage","nom"),
# ---------------- temps & météo ----------------
("de zon",["le soleil"],"A1","temps-meteo","nom"),("de regen",["la pluie"],"A1","temps-meteo","nom"),
("de sneeuw",["la neige"],"A1","temps-meteo","nom"),("de wind",["le vent"],"A2","temps-meteo","nom"),
("de wolk",["le nuage"],"A2","temps-meteo","nom"),("het onweer",["l'orage"],"B1","temps-meteo","nom"),
("de mist",["le brouillard"],"B1","temps-meteo","nom"),("de temperatuur",["la température"],"B1","temps-meteo","nom"),
("de lente",["le printemps"],"A2","temps-meteo","nom"),("de zomer",["l'été"],"A2","temps-meteo","nom"),
("de herfst",["l'automne"],"A2","temps-meteo","nom"),("de winter",["l'hiver"],"A2","temps-meteo","nom"),
# ---------------- nombres & dates ----------------
("dinsdag",["mardi"],"A1","nombres-dates","nom"),("woensdag",["mercredi"],"A1","nombres-dates","nom"),
("donderdag",["jeudi"],"A1","nombres-dates","nom"),("vrijdag",["vendredi"],"A1","nombres-dates","nom"),
("zaterdag",["samedi"],"A1","nombres-dates","nom"),("zondag",["dimanche"],"A1","nombres-dates","nom"),
("het jaar",["l'année"],"A1","nombres-dates","nom"),("de maand",["le mois"],"A1","nombres-dates","nom"),
("de week",["la semaine"],"A1","nombres-dates","nom"),("het uur",["l'heure"],"A1","nombres-dates","nom"),
("de minuut",["la minute"],"A2","nombres-dates","nom"),("gisteren",["hier"],"A1","nombres-dates","mot-outil"),
("altijd",["toujours"],"A1","nombres-dates","mot-outil"),("nooit",["jamais"],"A1","nombres-dates","mot-outil"),
("soms",["parfois"],"A2","nombres-dates","mot-outil"),("vaak",["souvent"],"A2","nombres-dates","mot-outil"),
# ---------------- nature & animaux ----------------
("de boom",["l'arbre"],"A1","nature-environnement","nom"),("de bloem",["la fleur"],"A1","nature-environnement","nom"),
("het bos",["la forêt"],"A2","nature-environnement","nom"),("de zee",["la mer"],"A1","nature-environnement","nom"),
("de rivier",["la rivière"],"A2","nature-environnement","nom"),("de berg",["la montagne"],"A2","nature-environnement","nom"),
("de hond",["le chien"],"A1","nature-environnement","nom"),("de kat",["le chat"],"A1","nature-environnement","nom"),
("het paard",["le cheval"],"A2","nature-environnement","nom"),("de vogel",["l'oiseau"],"A1","nature-environnement","nom"),
("het dier",["l'animal"],"A1","nature-environnement","nom"),("de lucht",["l'air"],"A2","nature-environnement","nom"),
("het klimaat",["le climat"],"B1","nature-environnement","nom"),("de vervuiling",["la pollution"],"B1","nature-environnement","nom"),
# ---------------- loisirs & sport ----------------
("het boek",["le livre"],"A1","loisirs-sport","nom"),("de film",["le film"],"A1","loisirs-sport","nom"),
("de muziek",["la musique"],"A1","loisirs-sport","nom"),("het spel",["le jeu"],"A1","loisirs-sport","nom"),
("de sport",["le sport"],"A1","loisirs-sport","nom"),("het voetbal",["le football"],"A2","loisirs-sport","nom"),
("de wandeling",["la promenade"],"A2","loisirs-sport","nom"),("het feest",["la fête"],"A2","loisirs-sport","nom"),
("de vrije tijd",["le temps libre"],"B1","loisirs-sport","nom"),("de hobby",["le loisir"],"B1","loisirs-sport","nom"),
# ---------------- travail & études ----------------
("het werk",["le travail"],"A1","travail-etudes","nom"),("de school",["l'école"],"A1","travail-etudes","nom"),
("de leraar",["l'enseignant"],"A2","travail-etudes","nom"),("de student",["l'étudiant"],"A2","travail-etudes","nom"),
("de les",["le cours"],"A2","travail-etudes","nom"),("het examen",["l'examen"],"A2","travail-etudes","nom"),
("het kantoor",["le bureau"],"A2","travail-etudes","nom"),("het salaris",["le salaire"],"B1","travail-etudes","nom"),
("de vergadering",["la réunion"],"B1","travail-etudes","nom"),("de opleiding",["la formation"],"B1","travail-etudes","nom"),
("het diploma",["le diplôme"],"B1","travail-etudes","nom"),("de stage",["le stage"],"B1","travail-etudes","nom"),
# ---------------- sentiments ----------------
("blij",["content"],"A1","sentiments","adjectif"),("verdrietig",["triste"],"A2","sentiments","adjectif"),
("boos",["fâché"],"A2","sentiments","adjectif"),("bang",["effrayé"],"A2","sentiments","adjectif"),
("moe",["fatigué"],"A1","sentiments","adjectif"),("trots",["fier"],"B1","sentiments","adjectif"),
("verrast",["surpris"],"B1","sentiments","adjectif"),("teleurgesteld",["déçu"],"B1","sentiments","adjectif"),
("nerveus",["nerveux"],"B1","sentiments","adjectif"),("rustig",["calme"],"A2","sentiments","adjectif"),
# ---------------- verbes fréquents ----------------
("zijn",["être"],"A1","verbes","verbe"),("gaan",["aller"],"A1","verbes","verbe"),
("komen",["venir"],"A1","verbes","verbe"),("doen",["faire"],"A1","verbes","verbe"),
("zien",["voir"],"A1","verbes","verbe"),("weten",["savoir"],"A1","verbes","verbe"),
("zeggen",["dire"],"A1","verbes","verbe"),("geven",["donner"],"A1","verbes","verbe"),
("vinden",["trouver"],"A1","verbes","verbe"),("werken",["travailler"],"A1","verbes","verbe"),
("wonen",["habiter"],"A1","verbes","verbe"),("eten",["manger"],"A1","verbes","verbe"),
("drinken",["boire"],"A1","verbes","verbe"),("slapen",["dormir"],"A1","verbes","verbe"),
("lopen",["marcher"],"A2","verbes","verbe"),("praten",["parler"],"A1","verbes","verbe"),
("lezen",["lire"],"A1","verbes","verbe"),("schrijven",["écrire"],"A1","verbes","verbe"),
("kopen",["acheter"],"A1","verbes","verbe"),("betalen",["payer"],"A2","verbes","verbe"),
("helpen",["aider"],"A2","verbes","verbe"),("vragen",["demander"],"A2","verbes","verbe"),
("antwoorden",["répondre"],"A2","verbes","verbe"),("leren",["apprendre"],"A1","verbes","verbe"),
("spelen",["jouer"],"A1","verbes","verbe"),("wachten",["attendre"],"A2","verbes","verbe"),
("zoeken",["chercher"],"A2","verbes","verbe"),("openen",["ouvrir"],"A2","verbes","verbe"),
("sluiten",["fermer"],"A2","verbes","verbe"),("brengen",["apporter"],"A2","verbes","verbe"),
("kiezen",["choisir"],"B1","verbes","verbe"),("proberen",["essayer"],"B1","verbes","verbe"),
("beslissen",["décider"],"B1","verbes","verbe"),("veranderen",["changer"],"B1","verbes","verbe"),
("verliezen",["perdre"],"B1","verbes","verbe"),("winnen",["gagner"],"B1","verbes","verbe"),
("bouwen",["construire"],"B1","verbes","verbe"),("groeien",["grandir"],"B1","verbes","verbe"),
# ---------------- adjectifs fréquents ----------------
("groot",["grand"],"A1","adjectifs","adjectif"),("klein",["petit"],"A1","adjectifs","adjectif"),
("nieuw",["nouveau"],"A1","adjectifs","adjectif"),("oud",["vieux"],"A1","adjectifs","adjectif"),
("goed",["bon"],"A1","adjectifs","adjectif"),("slecht",["mauvais"],"A1","adjectifs","adjectif"),
("mooi",["beau"],"A1","adjectifs","adjectif"),("lelijk",["laid"],"A2","adjectifs","adjectif"),
("snel",["rapide"],"A1","adjectifs","adjectif"),("langzaam",["lent"],"A2","adjectifs","adjectif"),
("warm",["chaud"],"A1","adjectifs","adjectif"),("koud",["froid"],"A1","adjectifs","adjectif"),
("duur",["cher"],"A2","adjectifs","adjectif"),("goedkoop",["bon marché"],"A2","adjectifs","adjectif"),
("makkelijk",["facile"],"A2","adjectifs","adjectif"),("moeilijk",["difficile"],"A1","adjectifs","adjectif"),
("sterk",["fort"],"A2","adjectifs","adjectif"),("zwak",["faible"],"B1","adjectifs","adjectif"),
("hoog",["haut"],"A2","adjectifs","adjectif"),("laag",["bas"],"A2","adjectifs","adjectif"),
("vol",["plein"],"A2","adjectifs","adjectif"),("leeg",["vide"],"A2","adjectifs","adjectif"),
("schoon",["propre"],"A2","adjectifs","adjectif"),("vuil",["sale"],"A2","adjectifs","adjectif"),
("belangrijk",["important"],"B1","adjectifs","adjectif"),("gevaarlijk",["dangereux"],"B1","adjectifs","adjectif"),
("veilig",["sûr"],"B1","adjectifs","adjectif"),("mogelijk",["possible"],"B1","adjectifs","adjectif"),
# ---------------- mots-outils ----------------
("maar",["mais"],"A1","mots-outils","mot-outil"),("omdat",["parce que"],"A2","mots-outils","mot-outil"),
("want",["car"],"A2","mots-outils","mot-outil"),("dus",["donc"],"A2","mots-outils","mot-outil"),
("ook",["aussi"],"A1","mots-outils","mot-outil"),("nog",["encore"],"A1","mots-outils","mot-outil"),
("al",["déjà"],"A1","mots-outils","mot-outil"),("hier",["ici"],"A1","mots-outils","mot-outil"),
("daar",["là"],"A1","mots-outils","mot-outil"),("waarom",["pourquoi"],"A1","mots-outils","mot-outil"),
("hoe",["comment"],"A1","mots-outils","mot-outil"),("wanneer",["quand"],"A1","mots-outils","mot-outil"),
("wie",["qui"],"A1","mots-outils","mot-outil"),("wat",["quoi"],"A1","mots-outils","mot-outil"),
("misschien",["peut-être"],"A2","mots-outils","mot-outil"),("bijna",["presque"],"A2","mots-outils","mot-outil"),
("genoeg",["assez"],"A2","mots-outils","mot-outil"),("samen",["ensemble"],"A2","mots-outils","mot-outil"),
("tegen",["contre"],"A2","mots-outils","mot-outil"),("zonder",["sans"],"A2","mots-outils","mot-outil"),
# ---------------- société & actualité ----------------
("de regering",["le gouvernement"],"B1","societe-actualite","nom"),("de wet",["la loi"],"B1","societe-actualite","nom"),
("de verkiezing",["l'élection"],"B2","societe-actualite","nom"),("de belasting",["l'impôt"],"B2","societe-actualite","nom"),
("de maatschappij",["la société"],"B2","societe-actualite","nom"),("de bevolking",["la population"],"B2","societe-actualite","nom"),
("de veiligheid",["la sécurité"],"B1","societe-actualite","nom"),("de vrijheid",["la liberté"],"B1","societe-actualite","nom"),
("de armoede",["la pauvreté"],"B2","societe-actualite","nom"),("de werkloosheid",["le chômage"],"B2","societe-actualite","nom"),
]
