# -*- coding: utf-8 -*-
"""Extension de la banque espagnole.

CES MOTS NE VIENNENT PAS DES LEXIQUES DU SITE : ils sont ajoutés pour le volume
et portent tous source="non-verifie". Même règle que pour le néerlandais et
l'anglais : vocabulaire courant, concret, peu ambigu. Les mots à double sens
marqués (el banco, la letra, el tiempo, la cuenta…) sont écartés exprès.
Conventions reprises des lexiques espagnols du site : noms avec article,
traduction française avec article, verbes à l'infinitif nu.
"""
# (mot, [traductions], niveau, categorie, classe)
EXT = [
# ---------------- famille & personnes ----------------
("el tío",["l'oncle"],"A2","famille","nom"),("la tía",["la tante"],"A2","famille","nom"),
("el primo",["le cousin"],"A2","famille","nom"),("la prima",["la cousine"],"A2","famille","nom"),
("el marido",["le mari"],"A2","famille","nom"),("la esposa",["l'épouse"],"A2","famille","nom"),
("los padres",["les parents"],"A1","famille","nom"),("el niño",["l'enfant"],"A1","famille","nom"),
("el vecino",["le voisin"],"A2","famille","nom"),("el compañero",["le camarade"],"A2","famille","nom"),
("el sobrino",["le neveu"],"B1","famille","nom"),("la sobrina",["la nièce"],"B1","famille","nom"),
("el chico",["le garçon"],"A1","famille","nom"),("la chica",["la fille (jeune)"],"A1","famille","nom"),
("el adulto",["l'adulte"],"B1","famille","nom"),("la pareja",["le couple"],"A2","famille","nom"),
# ---------------- nourriture ----------------
("el arroz",["le riz"],"A2","nourriture","nom"),("la sal",["le sel"],"A1","nourriture","nom"),
("el azúcar",["le sucre"],"A1","nourriture","nom"),("la mantequilla",["le beurre"],"A1","nourriture","nom"),
("el aceite",["l'huile"],"A2","nourriture","nom"),("la sopa",["la soupe"],"A2","nourriture","nom"),
("la ensalada",["la salade"],"A2","nourriture","nom"),("el pollo",["le poulet"],"A2","nourriture","nom"),
("el té",["le thé"],"A1","nourriture","nom"),("el zumo",["le jus"],"A1","nourriture","nom"),
("el vino",["le vin"],"A2","nourriture","nom"),("la cerveza",["la bière"],"A2","nourriture","nom"),
("el pastel",["le gâteau"],"A2","nourriture","nom"),("el chocolate",["le chocolat"],"A1","nourriture","nom"),
("la patata",["la pomme de terre"],"A1","nourriture","nom"),("la verdura",["le légume"],"A1","nourriture","nom"),
("el desayuno",["le petit-déjeuner"],"A2","nourriture","nom"),("la comida",["le repas"],"A2","nourriture","nom"),
("la cena",["le dîner"],"A2","nourriture","nom"),("el plato",["l'assiette"],"A2","nourriture","nom"),
("el tenedor",["la fourchette"],"A2","nourriture","nom"),("el cuchillo",["le couteau"],"A2","nourriture","nom"),
("la cuchara",["la cuillère"],"A2","nourriture","nom"),("la botella",["la bouteille"],"A1","nourriture","nom"),
("el hambre",["la faim"],"A2","nourriture","nom"),("la sed",["la soif"],"A2","nourriture","nom"),
("la naranja",["l'orange"],"A1","nourriture","nom"),("el tomate",["la tomate"],"A1","nourriture","nom"),
# ---------------- maison ----------------
("la casa",["la maison"],"A1","maison","nom"),("la puerta",["la porte"],"A1","maison","nom"),
("la ventana",["la fenêtre"],"A1","maison","nom"),("la mesa",["la table"],"A1","maison","nom"),
("la silla",["la chaise"],"A1","maison","nom"),("la cama",["le lit"],"A1","maison","nom"),
("la cocina",["la cuisine (pièce)"],"A1","maison","nom"),("el dormitorio",["la chambre"],"A1","maison","nom"),
("el jardín",["le jardin"],"A2","maison","nom"),("la pared",["le mur"],"A2","maison","nom"),
("el techo",["le toit"],"A2","maison","nom"),("la escalera",["l'escalier"],"A2","maison","nom"),
("la llave",["la clé"],"A1","maison","nom"),("la lámpara",["la lampe"],"A1","maison","nom"),
("el espejo",["le miroir"],"A2","maison","nom"),("la toalla",["la serviette"],"A2","maison","nom"),
("la manta",["la couverture"],"B1","maison","nom"),("el cajón",["le tiroir"],"B1","maison","nom"),
("el alquiler",["le loyer"],"B1","maison","nom"),("el piso",["l'appartement"],"A2","maison","nom"),
("el edificio",["l'immeuble"],"A2","maison","nom"),("el armario",["l'armoire"],"A2","maison","nom"),
("la nevera",["le réfrigérateur"],"A2","maison","nom"),("el suelo",["le sol"],"A2","maison","nom"),
# ---------------- corps & santé ----------------
("la cabeza",["la tête"],"A1","corps-sante","nom"),("la mano",["la main"],"A1","corps-sante","nom"),
("el pie",["le pied"],"A1","corps-sante","nom"),("el ojo",["l'œil"],"A1","corps-sante","nom"),
("la boca",["la bouche"],"A1","corps-sante","nom"),("la nariz",["le nez"],"A1","corps-sante","nom"),
("la oreja",["l'oreille"],"A1","corps-sante","nom"),("el brazo",["le bras"],"A1","corps-sante","nom"),
("la pierna",["la jambe"],"A1","corps-sante","nom"),("el corazón",["le cœur"],"A1","corps-sante","nom"),
("la espalda",["le dos"],"A2","corps-sante","nom"),("el diente",["la dent"],"A2","corps-sante","nom"),
("la piel",["la peau"],"B1","corps-sante","nom"),("la sangre",["le sang"],"B1","corps-sante","nom"),
("el hueso",["l'os"],"B1","corps-sante","nom"),("el dedo",["le doigt"],"A2","corps-sante","nom"),
("la rodilla",["le genou"],"A2","corps-sante","nom"),("el hombro",["l'épaule"],"A2","corps-sante","nom"),
("la garganta",["la gorge"],"B1","corps-sante","nom"),("la fiebre",["la fièvre"],"A2","corps-sante","nom"),
("la tos",["la toux"],"B1","corps-sante","nom"),("la herida",["la blessure"],"B1","corps-sante","nom"),
("el enfermero",["l'infirmier"],"A2","corps-sante","nom"),("la pastilla",["le comprimé"],"B1","corps-sante","nom"),
# ---------------- vêtements ----------------
("el pantalón",["le pantalon"],"A1","vetements","nom"),("la camisa",["la chemise"],"A1","vetements","nom"),
("el abrigo",["le manteau"],"A1","vetements","nom"),("la falda",["la jupe"],"A2","vetements","nom"),
("el jersey",["le pull"],"A2","vetements","nom"),("el calcetín",["la chaussette"],"A2","vetements","nom"),
("el sombrero",["le chapeau"],"A2","vetements","nom"),("el vestido",["la robe"],"A2","vetements","nom"),
("el cinturón",["la ceinture"],"B1","vetements","nom"),("el guante",["le gant"],"B1","vetements","nom"),
("la bufanda",["l'écharpe"],"B1","vetements","nom"),("la chaqueta",["la veste"],"A2","vetements","nom"),
("la bota",["la botte"],"B1","vetements","nom"),("el bolsillo",["la poche"],"A2","vetements","nom"),
("el zapato",["la chaussure"],"A1","vetements","nom"),
# ---------------- ville ----------------
("el pueblo",["le village"],"A2","ville","nom"),("la tienda",["le magasin"],"A1","ville","nom"),
("el mercado",["le marché"],"A2","ville","nom"),("la calle",["la rue"],"A1","ville","nom"),
("el puente",["le pont"],"A2","ville","nom"),("la iglesia",["l'église"],"A2","ville","nom"),
("el castillo",["le château"],"B1","ville","nom"),("el museo",["le musée"],"A2","ville","nom"),
("la biblioteca",["la bibliothèque"],"A2","ville","nom"),("el parque",["le parc"],"A1","ville","nom"),
("la farmacia",["la pharmacie"],"A2","ville","nom"),("la panadería",["la boulangerie"],"A2","ville","nom"),
("el ayuntamiento",["la mairie"],"B1","ville","nom"),("el barrio",["le quartier"],"B1","ville","nom"),
("la acera",["le trottoir"],"B1","ville","nom"),("la plaza",["la place"],"A2","ville","nom"),
# ---------------- transports & voyage ----------------
("el coche",["la voiture"],"A1","transports-voyage","nom"),("el avión",["l'avion"],"A1","transports-voyage","nom"),
("la bicicleta",["le vélo"],"A1","transports-voyage","nom"),("el barco",["le bateau"],"A2","transports-voyage","nom"),
("la carretera",["la route"],"A2","transports-voyage","nom"),("el aeropuerto",["l'aéroport"],"A2","transports-voyage","nom"),
("el equipaje",["les bagages"],"A2","transports-voyage","nom"),("la maleta",["la valise"],"A2","transports-voyage","nom"),
("el conductor",["le conducteur"],"A2","transports-voyage","nom"),("el pasajero",["le passager"],"B1","transports-voyage","nom"),
("el retraso",["le retard"],"B1","transports-voyage","nom"),("el puerto",["le port"],"B1","transports-voyage","nom"),
("el andén",["le quai"],"B1","transports-voyage","nom"),("el tren",["le train"],"A1","transports-voyage","nom"),
("la estación",["la gare"],"A1","transports-voyage","nom"),("la frontera",["la frontière"],"B1","transports-voyage","nom"),
# ---------------- météo ----------------
("la lluvia",["la pluie"],"A1","temps-meteo","nom"),("la nieve",["la neige"],"A1","temps-meteo","nom"),
("el viento",["le vent"],"A1","temps-meteo","nom"),("la nube",["le nuage"],"A2","temps-meteo","nom"),
("la tormenta",["l'orage"],"A2","temps-meteo","nom"),("la niebla",["le brouillard"],"B1","temps-meteo","nom"),
("el calor",["la chaleur"],"A2","temps-meteo","nom"),("el cielo",["le ciel"],"A2","temps-meteo","nom"),
("la estación del año",["la saison"],"A2","temps-meteo","nom"),("la primavera",["le printemps"],"A2","temps-meteo","nom"),
("el verano",["l'été"],"A1","temps-meteo","nom"),("el otoño",["l'automne"],"A2","temps-meteo","nom"),
("el invierno",["l'hiver"],"A1","temps-meteo","nom"),("el sol",["le soleil"],"A1","temps-meteo","nom"),
# ---------------- nature & environnement ----------------
("el árbol",["l'arbre"],"A1","nature-environnement","nom"),("la flor",["la fleur"],"A1","nature-environnement","nom"),
("la hierba",["l'herbe"],"A2","nature-environnement","nom"),("el bosque",["la forêt"],"A2","nature-environnement","nom"),
("la montaña",["la montagne"],"A2","nature-environnement","nom"),("el río",["la rivière"],"A2","nature-environnement","nom"),
("el mar",["la mer"],"A1","nature-environnement","nom"),("el lago",["le lac"],"A2","nature-environnement","nom"),
("la playa",["la plage"],"A2","nature-environnement","nom"),("la isla",["l'île"],"B1","nature-environnement","nom"),
("la piedra",["la pierre"],"B1","nature-environnement","nom"),("la arena",["le sable"],"B1","nature-environnement","nom"),
("el animal",["l'animal"],"A1","nature-environnement","nom"),("el pájaro",["l'oiseau"],"A1","nature-environnement","nom"),
("el perro",["le chien"],"A1","nature-environnement","nom"),("el gato",["le chat"],"A1","nature-environnement","nom"),
("el caballo",["le cheval"],"A2","nature-environnement","nom"),("la vaca",["la vache"],"A2","nature-environnement","nom"),
# ---------------- loisirs & sport ----------------
("el equipo",["l'équipe"],"A2","loisirs-sport","nom"),("el jugador",["le joueur"],"A2","loisirs-sport","nom"),
("la pelota",["le ballon"],"A1","loisirs-sport","nom"),("la natación",["la natation"],"A2","loisirs-sport","nom"),
("el paseo",["la promenade"],"A2","loisirs-sport","nom"),("las vacaciones",["les vacances"],"A1","loisirs-sport","nom"),
("la fiesta",["la fête"],"A2","loisirs-sport","nom"),("la canción",["la chanson"],"A1","loisirs-sport","nom"),
("el baile",["la danse"],"A2","loisirs-sport","nom"),("el dibujo",["le dessin"],"B1","loisirs-sport","nom"),
("el público",["le public"],"B1","loisirs-sport","nom"),("el estadio",["le stade"],"B1","loisirs-sport","nom"),
("la película",["le film"],"A1","loisirs-sport","nom"),("el libro",["le livre"],"A1","loisirs-sport","nom"),
# ---------------- travail & études ----------------
("la escuela",["l'école"],"A1","travail-etudes","nom"),("el profesor",["l'enseignant"],"A1","travail-etudes","nom"),
("el alumno",["l'élève"],"A1","travail-etudes","nom"),("el estudiante",["l'étudiant"],"A1","travail-etudes","nom"),
("la lección",["la leçon"],"A1","travail-etudes","nom"),("los deberes",["les devoirs"],"A2","travail-etudes","nom"),
("el examen",["l'examen"],"A2","travail-etudes","nom"),("el aula",["la salle de classe"],"A2","travail-etudes","nom"),
("el título",["le diplôme"],"B1","travail-etudes","nom"),("la fábrica",["l'usine"],"B1","travail-etudes","nom"),
("el obrero",["l'ouvrier"],"B1","travail-etudes","nom"),("el sueldo",["le salaire"],"B1","travail-etudes","nom"),
("el plazo",["l'échéance"],"B2","travail-etudes","nom"),("el taller",["l'atelier"],"B1","travail-etudes","nom"),
# ---------------- sentiments ----------------
("la alegría",["la joie"],"B1","sentiments","nom"),("la tristeza",["la tristesse"],"B1","sentiments","nom"),
("el miedo",["la peur"],"A2","sentiments","nom"),("la ira",["la colère"],"B1","sentiments","nom"),
("la esperanza",["l'espoir"],"B1","sentiments","nom"),("el amor",["l'amour"],"A2","sentiments","nom"),
("la vergüenza",["la honte"],"B2","sentiments","nom"),("el orgullo",["la fierté"],"B2","sentiments","nom"),
("el aburrimiento",["l'ennui"],"B2","sentiments","nom"),("los celos",["la jalousie"],"B2","sentiments","nom"),
("la confianza",["la confiance"],"B1","sentiments","nom"),("el alivio",["le soulagement"],"B2","sentiments","nom"),
# ---------------- communication ----------------
("la palabra",["le mot"],"A1","communication","nom"),("la frase",["la phrase"],"A2","communication","nom"),
("la respuesta",["la réponse"],"A1","communication","nom"),("el mensaje",["le message"],"A1","communication","nom"),
("el periódico",["le journal"],"A2","communication","nom"),("el anuncio",["la publicité"],"B1","communication","nom"),
("el significado",["la signification"],"B1","communication","nom"),("el error",["l'erreur"],"A2","communication","nom"),
("la historia",["l'histoire"],"A2","communication","nom"),("el discurso",["le discours"],"B2","communication","nom"),
("el silencio",["le silence"],"B1","communication","nom"),("el rumor",["la rumeur"],"B2","communication","nom"),
# ---------------- verbes ----------------
("caminar",["marcher"],"A1","verbes","verbe"),("correr",["courir"],"A1","verbes","verbe"),
("nadar",["nager"],"A2","verbes","verbe"),("dormir",["dormir"],"A1","verbes","verbe"),
("comprar",["acheter"],"A1","verbes","verbe"),("vender",["vendre"],"A2","verbes","verbe"),
("pagar",["payer"],"A2","verbes","verbe"),("cocinar",["cuisiner"],"A2","verbes","verbe"),
("lavar",["laver"],"A2","verbes","verbe"),("limpiar",["nettoyer"],"A2","verbes","verbe"),
("abrir",["ouvrir"],"A1","verbes","verbe"),("cerrar",["fermer"],"A1","verbes","verbe"),
("construir",["construire"],"B1","verbes","verbe"),("reparar",["réparer"],"B1","verbes","verbe"),
("tirar",["jeter"],"B1","verbes","verbe"),("empujar",["pousser"],"B1","verbes","verbe"),
("prestar",["prêter"],"B1","verbes","verbe"),("elegir",["choisir"],"A2","verbes","verbe"),
("decidir",["décider"],"B1","verbes","verbe"),("intentar",["essayer"],"A2","verbes","verbe"),
("ganar",["gagner"],"A2","verbes","verbe"),("perder",["perdre"],"A2","verbes","verbe"),
("olvidar",["oublier"],"A2","verbes","verbe"),("reír",["rire"],"A2","verbes","verbe"),
("llorar",["pleurer"],"A2","verbes","verbe"),("cantar",["chanter"],"A1","verbes","verbe"),
("bailar",["danser"],"A1","verbes","verbe"),("dibujar",["dessiner"],"A2","verbes","verbe"),
("enseñar",["enseigner"],"B1","verbes","verbe"),("explicar",["expliquer"],"B1","verbes","verbe"),
("escuchar",["écouter"],"A1","verbes","verbe"),("viajar",["voyager"],"A2","verbes","verbe"),
("llegar",["arriver"],"A2","verbes","verbe"),("esperar",["attendre"],"A2","verbes","verbe"),
("ayudar",["aider"],"A1","verbes","verbe"),("prohibir",["interdire"],"B2","verbes","verbe"),
("crecer",["grandir"],"B1","verbes","verbe"),("enviar",["envoyer"],"A2","verbes","verbe"),
("recibir",["recevoir"],"B1","verbes","verbe"),("llevar",["porter"],"B1","verbes","verbe"),
("leer",["lire"],"A1","verbes","verbe"),("escribir",["écrire"],"A1","verbes","verbe"),
("trabajar",["travailler"],"A1","verbes","verbe"),("estudiar",["étudier"],"A1","verbes","verbe"),
# ---------------- adjectifs ----------------
("grande",["grand"],"A1","adjectifs","adjectif"),("pequeño",["petit"],"A1","adjectifs","adjectif"),
("nuevo",["nouveau"],"A1","adjectifs","adjectif"),("viejo",["vieux"],"A1","adjectifs","adjectif"),
("bueno",["bon"],"A1","adjectifs","adjectif"),("malo",["mauvais"],"A1","adjectifs","adjectif"),
("bonito",["joli"],"A1","adjectifs","adjectif"),("feo",["laid"],"A2","adjectifs","adjectif"),
("rápido",["rapide"],"A1","adjectifs","adjectif"),("lento",["lent"],"A2","adjectifs","adjectif"),
("caliente",["chaud"],"A1","adjectifs","adjectif"),("frío",["froid"],"A1","adjectifs","adjectif"),
("caro",["cher"],"A2","adjectifs","adjectif"),("barato",["bon marché"],"A2","adjectifs","adjectif"),
("fácil",["facile"],"A1","adjectifs","adjectif"),("difícil",["difficile"],"A1","adjectifs","adjectif"),
("fuerte",["fort"],"A2","adjectifs","adjectif"),("débil",["faible"],"B1","adjectifs","adjectif"),
("alto",["haut"],"A2","adjectifs","adjectif"),("bajo",["bas"],"A2","adjectifs","adjectif"),
("lleno",["plein"],"A2","adjectifs","adjectif"),("vacío",["vide"],"A2","adjectifs","adjectif"),
("limpio",["propre"],"A2","adjectifs","adjectif"),("sucio",["sale"],"A2","adjectifs","adjectif"),
("peligroso",["dangereux"],"B1","adjectifs","adjectif"),("seguro",["sûr"],"B1","adjectifs","adjectif"),
("pesado",["lourd"],"A2","adjectifs","adjectif"),("ligero",["léger"],"A2","adjectifs","adjectif"),
("ancho",["large"],"B1","adjectifs","adjectif"),("estrecho",["étroit"],"B1","adjectifs","adjectif"),
("profundo",["profond"],"B1","adjectifs","adjectif"),("ruidoso",["bruyant"],"B1","adjectifs","adjectif"),
("cansado",["fatigué"],"A2","adjectifs","adjectif"),("contento",["content"],"A1","adjectifs","adjectif"),
("triste",["triste"],"A1","adjectifs","adjectif"),("listo",["prêt"],"A2","adjectifs","adjectif"),
("ocupado",["occupé"],"A2","adjectifs","adjectif"),("útil",["utile"],"A2","adjectifs","adjectif"),
("inútil",["inutile"],"B1","adjectifs","adjectif"),("joven",["jeune"],"A1","adjectifs","adjectif"),
# ---------------- mots-outils ----------------
("pero",["mais"],"A1","mots-outils","mot-outil"),("porque",["parce que"],"A1","mots-outils","mot-outil"),
("también",["aussi"],"A1","mots-outils","mot-outil"),("ya",["déjà"],"A2","mots-outils","mot-outil"),
("aquí",["ici"],"A1","mots-outils","mot-outil"),("allí",["là-bas"],"A1","mots-outils","mot-outil"),
("por qué",["pourquoi"],"A1","mots-outils","mot-outil"),("cómo",["comment"],"A1","mots-outils","mot-outil"),
("cuándo",["quand"],"A1","mots-outils","mot-outil"),("dónde",["où"],"A1","mots-outils","mot-outil"),
("quizás",["peut-être"],"A2","mots-outils","mot-outil"),("casi",["presque"],"A2","mots-outils","mot-outil"),
("bastante",["assez"],"A2","mots-outils","mot-outil"),("juntos",["ensemble"],"A2","mots-outils","mot-outil"),
("contra",["contre"],"A2","mots-outils","mot-outil"),("sin",["sans"],"A1","mots-outils","mot-outil"),
("entre",["entre"],"A2","mots-outils","mot-outil"),("durante",["pendant"],"A2","mots-outils","mot-outil"),
("antes",["avant"],"A1","mots-outils","mot-outil"),("después",["après"],"A1","mots-outils","mot-outil"),
("siempre",["toujours"],"A1","mots-outils","mot-outil"),("nunca",["jamais"],"A1","mots-outils","mot-outil"),
("a menudo",["souvent"],"A2","mots-outils","mot-outil"),("a veces",["parfois"],"A2","mots-outils","mot-outil"),
("en todas partes",["partout"],"B1","mots-outils","mot-outil"),("nada",["rien"],"A1","mots-outils","mot-outil"),
("todo",["tout"],"A1","mots-outils","mot-outil"),("alguien",["quelqu'un"],"A2","mots-outils","mot-outil"),
("nadie",["personne (aucun)"],"A2","mots-outils","mot-outil"),("mucho",["beaucoup"],"A1","mots-outils","mot-outil"),
# ---------------- société & actualité ----------------
("el gobierno",["le gouvernement"],"B1","societe-actualite","nom"),("la ley",["la loi"],"B1","societe-actualite","nom"),
("las elecciones",["les élections"],"B2","societe-actualite","nom"),("el impuesto",["l'impôt"],"B2","societe-actualite","nom"),
("la población",["la population"],"B2","societe-actualite","nom"),("la libertad",["la liberté"],"B1","societe-actualite","nom"),
("la seguridad",["la sécurité"],"B1","societe-actualite","nom"),("la guerra",["la guerre"],"B1","societe-actualite","nom"),
("la paz",["la paix"],"B1","societe-actualite","nom"),("el ciudadano",["le citoyen"],"B2","societe-actualite","nom"),
("el tribunal",["le tribunal"],"B2","societe-actualite","nom"),("la cárcel",["la prison"],"B2","societe-actualite","nom"),
("la huelga",["la grève"],"B2","societe-actualite","nom"),("la encuesta",["le sondage"],"B2","societe-actualite","nom"),
("la pobreza",["la pauvreté"],"B2","societe-actualite","nom"),("el paro",["le chômage"],"B2","societe-actualite","nom"),
]
